com.thoughtworks.xstream.converters.ConversionException: Cannot construct jetbrains.communicator.util.TreeState as it does not have a no-args constructor