regression: fix server show error regression: fix mem leak — dispose module info (otherwise, out module listeners are not disposed) improve trace server calls — print method name instead of id
test data for EA-31230 (is not yet fixed)

java.lang.ClassCastException: com.intellij.javascript.flex.MxmlParserDefinition$MxmlFile cannot be cast to com.intellij.lang.javascript.psi.ecmal4.JSClass
	at com.intellij.flex.uiDesigner.mxml.MxmlWriter.processDefaultProperty(MxmlWriter.java:578)
	at com.intellij.flex.uiDesigner.mxml.MxmlWriter.processTagChildren(MxmlWriter.java:309)
	at com.intellij.flex.uiDesigner.mxml.MxmlWriter.processElements(MxmlWriter.java:233)
	at com.intellij.flex.uiDesigner.mxml.MxmlWriter.write(MxmlWriter.java:82)
	at com.intellij.flex.uiDesigner.Client.writeDocumentFactory(Client.java:454)
	at com.intellij.flex.uiDesigner.Client.registerDocumentFactoryIfNeed(Client.java:410)
	at com.intellij.flex.uiDesigner.Client.openDocument(Client.java:287)
	at com.intellij.flex.uiDesigner.DesignerApplicationManager$FirstOpenDocumentTask.openDocument(DesignerApplicationManager.java:404)
	at com.intellij.flex.uiDesigner.DesignerApplicationManager$FirstOpenDocumentTask.run(DesignerApplicationManager.java:529)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$TaskRunnable.run(ProgressManagerImpl.java:457)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:178)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:206)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:169)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$7.run(ProgressManagerImpl.java:366)
	at com.intellij.openapi.application.impl.ApplicationImpl$6.run(ApplicationImpl.java:418)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)
	at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:137)